### ISSUE TITLE
Should Ed25519Signature2020 be in the context?

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/cit-vocab#2]
The context in https://github.com/digitalbazaar/cit-context does not declare `Ed25519Signature2020` like done here.  Which version is correct?

**Comment by dlongley** [comment]
The one without `Ed25519Signature2020` is correct.

**Comment by davidlehn** [comment]
Fixed in https://github.com/digitalbazaar/cit-vocab/commit/cdbd6192fa9cf71d2cba4aa99ade8a17ef7f812c.
